#!/bin/bash

docker stop lazyllm
docker rm lazyllm

docker run -itd --name lazyllm --restart=always \
    -v /home/lianghao/github:/github \
    -v /home/lianghao/logs/lazyllm:/root/logs \
    -p 10010-10020:10010-10020 \
    --env-file .env \
    lazyllm:250827-3
