#!/bin/bash

docker stop lazyllm
docker rm lazyllm

docker run -itd --name lazyllm --restart=always \
    -v /home/lianghao/github:/github \
    -v /home/lianghao/logs/lazyllm:/root/logs \
    -p 10001-10002:10001-10002 \
    --env-file .env \
    lazyllm:250811-2

