services:
  searxng:
    container_name: searxng
    image: 127.0.0.1:9869/searxng:2025.5.7-f52cd3f00
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - /home/lianghao/github/LazyLLM/docker/searxng:/etc/searxng:rw
    environment:
      - SEARXNG_BASE_URL=https://${SEARXNG_HOSTNAME:-localhost}/
      - UWSGI_WORKERS=${SEARXNG_UWSGI_WORKERS:-4}
      - UWSGI_THREADS=${SEARXNG_UWSGI_THREADS:-4}
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
    extra_hosts:
      - "host.docker.internal:host-gateway"